services:
  #docker compose build to just build the image,
  #docker compose up -build to build and create a container locally.
  #docker compose push to push to hub.
  mubank:
    container_name: mubank-front
    build: .
    image: week066/mubank_frontend:latest
    ports:
      - 4000:4000
    expose:
      - 4000

